version: 2.1

jobs:
  build: 
    docker:
      - image: cimg/base:2021.04
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: 
          name: build step
          command: |
            echo $DOCKERHUB_USERNAME
            echo Hello
      - run:
          name: The Second Step
          command:
            ls -al
            echo 'Files in my repo'
