version: 2.1

jobs:
  hello-job:
    docker:
      - image: alpine3.15
    steps:
      - run: 
        name: the first step
        command: | 
          echo 'hello world'

workflows:
  my-workflow:
    jobs:
      - hello-job