version: 2.1

jobs:
  Hello-World:
    docker:
      - image: cimg/base:2021.04
    steps:
      - run:
          name: Hello world step
          command: |
            echo Here I am!!
            ps -s 
            echo Process running now!!

  Fetch-code: 
    docker:
      - image: cimg/base:2021.04
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: 
          name: build step
          command: |
            echo $DOCKERHUB_USERNAM
            echo Hello
      - run:
          name: The Second Step
          command: |
            ls -al
            echo 'Files in my repo'
  
  Using-Node:
    docker:
      - image: cimg/node:17.2
    steps:
      - run:
          name: Running the Node container
          command: 
            node -v # Node version here

  Now-Complete:
    docker:
      - image: alpine:3.15
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - run:
          name: Approval complete
          command: 
            echo "The work is now complete."

workflows:
  Example-worflow:
    jobs:
      - Hello-World
      - Fetch-code:
          requires: 
            - Hello-World
      - Using-Node:
          requires: 
            - Hello-World
      - Hold-for-Approval:
          type: approval
          requires:
            - Fetch-code
            - Using-Node
      - Now-Complete:
          requires:
            - Hold-for-Approval