version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:3.9.5
  working_directory: ~/project

prepare_tox: &prepare_tox
  run:
    name: Installing tox
    commands: |
      sudo pip install --upgrade pip
      pip install --user tox

jobs:
  test_app: 
    <<: *defaults
    working_directory: ~/project/ci-and-publishing/Titanic-fast-api
    steps:
      - checkout
      - *prepare_tox
      - run:
          name: Running app tests
          commands:
            tox
        
workflows:
  jobs:
    - test_app   
