version: 2.1

jobs:
  hello-job: 
    docker:
      - image: alpine:3.15
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - run: 
          name: the first step
          command:
            echo $DOCKERHUB_USERNAME
