version: 2.1

defaults: &defaults
  docker:
    - image: circleci/python:3.9.5
  working_directory: ~/project

prepare_tox: &prepare_tox
  run:
    name: Installing tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox

jobs:
  test_app: 
    <<: *defaults
    working_directory: ~/project/ci-and-publishing/Titanic-fast-api
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Running app tests
          command:
            tox
  
  deploy_to_heroku:
    <<: *defaults
    steps:
      - checkout:
        path: ~/project
      - *prepare_tox
      - run:
          name: Deploying to heroku
          command:
            git subtree push --prefix ci-and-publishing/Titanic-fast-api https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git

workflows:
  my-worflow:
    jobs:
      - test_app  
      - deploy_to_heroku:
          requires:
            - test_app
